dist: focal

branches:
  only:
    - "master"

os: linux

services:
  - docker

language: c

compiler:
  - gcc

addons:
  apt:
    packages:
      - ack
      - axel
      - cpanminus
      - libtest-base-perl
      - libtext-diff-perl
      - liburi-perl
      - libwww-perl
      - libtest-longstring-perl
      - liblist-moreutils-perl
      - libgd-dev
      - time
      - cmake
      - curl
      - wget
      - gnupg
      - ca-certificates
      - lsb-release

before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)

cache:
  apt: true
  directories:
  - download-cache
  - docker_images

env:
  global:
    - JOBS=3
    - NGX_BUILD_JOBS=$JOBS
    - TEST_NGINX_MYSQL_PATH=/var/run/mysqld/mysqld.sock
    - TEST_NGINX_SLEEP=0.006
  jobs:
    - DB_VERSION=mysql:5.7
    - DB_VERSION=mysql:8.0
    - DB_VERSION=mariadb:5.5
    - DB_VERSION=mariadb:10.0
    - DB_VERSION=mariadb:10.1
    - DB_VERSION=mariadb:10.2
    - DB_VERSION=mariadb:10.3
    - DB_VERSION=mariadb:11.4
    - DB_VERSION=mariadb:11.8
    - DB_VERSION=mariadb:12.2

install:
  - if [ ! -d download-cache ]; then mkdir download-cache; fi
  - git clone https://github.com/openresty/test-nginx.git
  - git clone https://github.com/spacewander/lua-resty-rsa.git ../lua-resty-rsa
  - git clone https://github.com/fffonion/lua-resty-openssl.git ../lua-resty-openssl
  - wget -O - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
  - echo "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/openresty.list
  - sudo apt-get update
  - sudo apt-get -y install openresty-debug

before_script:
  - docker load -i docker_images/images.tar || true
  - sudo systemctl stop mysql
  - ./.travis/initializedb.sh

script:
  - sudo cpanm --notest Test::Nginx IPC::Run Test2::Util > build.log 2>&1 || (cat build.log && exit 1)
  - (sudo cpanm --notest ./test-nginx > build.log 2>&1 || (cat build.log && exit 1))
  - export PATH=/usr/local/openresty-debug/nginx/sbin:$PATH
  - TEST_SUBSYSTEM=http prove -I. -I./test-nginx/inc -I./test-nginx/lib -r t
  - TEST_SUBSYSTEM=stream prove -I. -I./test-nginx/inc -I./test-nginx/lib -r t
